name: Build BorderlessGaming

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build BorderlessGaming.sln -c Release



      - name: Find EXE
        run: |
          dir /s /b *.exe

      - name: Upload Built EXE
        uses: actions/upload-artifact@v4
        with:
          name: BorderlessGaming
          path: |
            **\Release\*.exe
